### ISSUE TITLE
Admin Feature Request: show region alongside tags before submitting results

### ISSUE THREAD

**Issue by VestboyMyst** [ripgarpr/garpr#153]
Self explanatory. Currently region will show up when suggesting merges. Right now when entering results, you see tags for all regions but not which region each tag is from. Add in the region to the end of each tag similarly to other search boxes.

![image](https://cloud.githubusercontent.com/assets/8193563/19990166/02aec020-a202-11e6-95ed-31351d728bb7.png)

**Comment by BrandonCookeDev** [comment]
Yeah so actually #106 was actually supposed to fix this exact problem, but ironically this is the only box it didn't end up fixing (due to a bug).

I was going to try to find time to fix this and the other issues after my school project is over. Should not be too long from now.

**Comment by BrandonCookeDev** [comment]
Also extra information on the Bug:
#106 was fixed by adding a function into the PlayerService that tacks on an extra JS property to all Player JS objects (This property is called "Typeahead"). 

You can see this change at:
https://github.com/ripgarpr/garpr/pull/150/files#diff-5f6251601d7c16cbcfed7d2829ebc0cd

However, when the PendingTournament page loads, Player information is not loaded from the PlayersService. It is likely loaded via the PendingTournament controller or a PendingTournament service. Pressumably, this additional function will need to be applied in that service in order to fix the bug.
Alternatively, this bug can probably be fixed by just adding on the "Typeahead" property via the Python api when we send a list of players back to the UI.

**Comment by BrandonCookeDev** [comment]
Fixed by f650cadf8dd30eb0869cc5f379b6a569fc7e2ff9
