### ISSUE TITLE
feature req: display uncertainty better

### ISSUE THREAD

**Issue by VestboyMyst** [ripgarpr/garpr#47]
not sure what units the current uncertainty is in, but convert to +/- point value, and add to the right of where points are currently displayed on the main rankings page

that, or to keep the aesthetics, add in the ability to hover over the current scores and see the uncertainty, as it does on the player pages

on the player pages the uncertainty should probably be displayed next to the rating as its own text field, not only when not hovered over

**Comment by jessemtso** [comment]
this should be pretty easy, cookie should be able to knock this out

**Comment by BrandonCookeDev** [comment]
are there examples of this conversion? I'm not too familiar even with the standard + - system even, let alone the Trueskill uncertainty measure

**Comment by Jamesargy6** [comment]
So, currently we are using the following formula to display a user's skill (this is also used to generate our list of rankings): 

PSkill = sigma - (3*mu) _or_ rawSkill - (3*uncertainty).

This is done in order to deflate player's skills who have few results, to "Assume the worst" and not grant a player high rankings off of a few good results. I think this is better than using the raw score for ranking purposes. However, it would be nice for players to hover over their scores an view these two values (they are already able to do so on the player details screen).

**Comment by BrandonCookeDev** [comment]
This should be fixed by e6044a8218b37d3a28f9bbd7bae30404bea66f3c

Added a button that shows the formulas, and subsequent click hides them.
We may need to adjust the UI a bit (aligning the button that shows/hides the formulas) but this should be squared away.
