### ISSUE TITLE
Rating system using challonge API

### ISSUE THREAD

**Issue by shadowfox87** [ripgarpr/garpr#89]
If True Skill is being used as the ranking method, is it possible to add options for which ranking method the user wants to use such as Elo or Gicko2 or FIDE? Also, set score 2-1 vs 2-0 should be considered because many tournament organizations calculate the total wins/loses as part of Elo rating.

**Comment by jessemtso** [comment]
yes, ratings systems are pluggable. however, we're not currently storing game counts (some APIs dont even have them), so that's not super feasible.

our general flow is, you send us a pull-request to prove youre 'worthy' (pick an issue from the issues tracker), and then we'll add you to the slack and project :)
